# Use the official Rust image as a base
FROM rust:1.89-slim-bookworm

RUN apt-get update && apt-get install -y postgresql-client && apt-get clean

# Set the working directory
WORKDIR /app

# Install required dependencies
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy the Cargo.toml and Cargo.lock files
COPY Cargo.toml Cargo.lock ./

# Pre-fetch the dependencies to leverage Docker's cache
RUN cargo fetch

RUN cargo install cargo-watch

# Copy the source code
# COPY src ./src
# COPY tests ./tests

# # Expose the port your Axum app runs on
# EXPOSE 3000
#
# # Use cargo run for development
# CMD ["cargo", "run"]
